### ISSUE TITLE
Doesen't work for RAW video format

### ISSUE THREAD

**Issue by realSZ27** [pratikpatel8982/yt-dlp-hianime#1]
New episodes sometimes have raw as their type, rather than sub or dub.

An example is [this Suicide Squad](https://hianime.to/watch/suicide-squad-isekai-19252?ep=126677) episode (for now).

**Comment by pratikpatel8982** [comment]
Well It has

**Comment by pratikpatel8982** [comment]
I found another URL: https://hianime.to/watch/duel-masters-king-raw-17515?ep=90084

It also has the RAW type. Will fix this ASAP
