### ISSUE TITLE
Filler Episodes

### ISSUE THREAD

**Issue by reavessm** [pratikpatel8982/yt-dlp-hianime#4]
This seems to skip filler episodes.  Visiting `https://hianime.to/watch/clannad-418` in the browser shows 23 episodes, with 5 marked as filler.  Running the command in the cli downloads the 18 non-filler episodes.  Is there an option to include these?

**Comment by pratikpatel8982** [comment]
I am updating code to fix this.

**Comment by pratikpatel8982** [comment]
Issue fixed, update the plugin.

**Comment by reavessm** [comment]
Thanks!  That did it!
